### ISSUE TITLE
Add support for Gutenberg's 'align-wide'

### ISSUE THREAD

**Issue by melchoyce** [melchoyce/melchoyce.design#2]
See: https://github.com/WordPress/gutenberg/blob/master/docs/themes.md#wide-alignment

I'd like to add add wide images. Thinking 1000px wide?

**Comment by melchoyce** [comment]
<img width="1433" alt="screen shot 2018-01-12 at 4 34 56 pm" src="https://user-images.githubusercontent.com/2846578/34896128-9416456e-f7b6-11e7-9a2c-95478357c90b.png">

Can you help me get this styled right, so it takes up 1000px of space and is correctly centered?

**Comment by ryelle** [comment]
Done, I changed the max-width that's sent to photon to be 1000px wide, so your image is correctly 1000px now. this does mean that the full-width image won't work, because the photon'd image will always max out at 1000px.

**Comment by melchoyce** [comment]
That's fine, I don't intend on using full-width.

Thanks!
