### ISSUE TITLE
Increase line-height of li

### ISSUE THREAD

**Issue by melchoyce** [melchoyce/melchoyce.design#3]
From 1.4 to 1.6.

**Comment by ryelle** [comment]
Hah you'd actually decreased this yourself via customizer. I've deleted the `line-height` there, but you should check if you want to remove the `padding-bottom: 6px;` too.

**Comment by melchoyce** [comment]
Wow, go me 😓

**Comment by melchoyce** [comment]
I want to keep the padding, can you add it to my stylesheet?

**Comment by ryelle** [comment]
done 👍
